export enum EscrowStatus {
  PENDING = 'PENDING',
  ON_CHAIN = 'ON_CHAIN',
  PROCESSING = 'PROCESSING',
  SETTLED = 'SETTLED',
  REDEEMED = 'REDEEMED',
  EXPIRED = 'EXPIRED',
  CANCELED = 'CANCELED',
  FAILED = 'FAILED',
}
