/**
 * AUTO-GENERATED by scripts/oracle-mine/scripts/fetch-icons.ts — DO NOT EDIT.
 *
 * Maps each oracle token's canonical ticker to the same-origin path of its
 * baked icon under the Vite `public/` root. These icons are served from
 * muhaven.app itself, so the COEP `require-corp` header (load-bearing for
 * the FHE WASM's SharedArrayBuffer) does not block them — unlike the
 * third-party rwa.xyz URLs in `token.icon_url`.
 *
 * Regenerate after an icon changes: `npm run fetch:icons` (then rebuild +
 * push the frontend). No timestamp is emitted, so an unchanged icon set
 * produces a zero-diff re-run.
 */
export const TOKEN_ICON_MANIFEST: Readonly<Record<string, string>> = {
  "BUIDL": "/token-icons/BUIDL.png",
  "CETES": "/token-icons/CETES.png",
  "EUTBL": "/token-icons/EUTBL.png",
  "MUon": "/token-icons/MUon.png",
  "NVDAon": "/token-icons/NVDAon.png",
  "ONyc": "/token-icons/ONyc.png",
  "STRCx": "/token-icons/STRCx.png",
  "syrupUSDC": "/token-icons/syrupUSDC.png",
  "TSLAx": "/token-icons/TSLAx.png",
  "USDY": "/token-icons/USDY.png",
  "USYC": "/token-icons/USYC.png",
} as const
