import { TOKEN_ICON_MANIFEST } from '@/data/tokenIcons.generated'

/**
 * Marketplace token-icon resolution.
 *
 * The marketplace cards + token-detail hero used to render
 * `token.icon_url` directly — a third-party rwa.xyz S3 URL. The SPA is
 * served with `Cross-Origin-Embedder-Policy: require-corp` (load-bearing
 * for the FHE WASM's `SharedArrayBuffer`), which blocks cross-origin
 * subresources, so those icons rendered broken.
 *
 * The fix bakes each token's icon into the frontend bundle under
 * `public/token-icons/` (generated by `scripts/oracle-mine/scripts/fetch-icons.ts`).
 * Those are served same-origin from muhaven.app, so COEP is satisfied.
 * The resolver maps a ticker → its baked same-origin path; it deliberately
 * does NOT fall back to `token.icon_url` (that S3 URL is always
 * COEP-blocked, so trying it only reintroduces the broken image + a
 * console error). A ticker with no baked icon resolves to `null`, and the
 * UI renders a monogram instead.
 */

// Case-insensitive index, built once. The manifest keys are canonical
// tickers (e.g. `syrupUSDC`, `MUon`); lookups elsewhere in the app are
// case-insensitive (see oracle-tokens store), so mirror that here.
const byLowerTicker: ReadonlyMap<string, string> = new Map(
  Object.entries(TOKEN_ICON_MANIFEST).map(([ticker, path]) => [ticker.toLowerCase(), path]),
)

/**
 * Resolve a token's baked, same-origin icon path, or `null` when no icon
 * was baked for that ticker (caller should render a monogram).
 */
export function resolveTokenIconUrl(ticker: string | null | undefined): string | null {
  if (!ticker) return null
  return byLowerTicker.get(ticker.toLowerCase()) ?? null
}

/**
 * Single-character monogram for the no-icon fallback. Uppercased first
 * character of the ticker; `?` when the ticker is empty/absent.
 */
export function tokenMonogram(ticker: string | null | undefined): string {
  const first = ticker?.trim()?.[0]
  return first ? first.toUpperCase() : '?'
}
